---
http_interactions:
- request:
    method: post
    uri: https://ci.appveyor.com/api/environments
    body:
      encoding: UTF-8
      string: '{"deploymentEnvironmentId":32724,"name":"production","provider":"FTP","settings":{"providerSettings":[{"name":"server","value":{"value":"ftp.server.com","isEncrypted":false}},{"name":"username","value":{"value":"ftp-user","isEncrypted":false}},{"name":"password","value":{"value":"password","isEncrypted":true}}],"environmentVariables":[{"name":"my-var","value":{"value":"123","isEncrypted":false}}]}}'
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Strict-Transport-Security:
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      Date:
      - Sun, 26 Nov 2017 10:33:37 GMT
      Content-Length:
      - '72'
    body:
      encoding: UTF-8
      string: '{"message":"Deployment environment with specified name already exists."}'
    http_version: 
  recorded_at: Sun, 26 Nov 2017 10:33:38 GMT
recorded_with: VCR 3.0.3
