---
http_interactions:
- request:
    method: delete
    uri: https://ci.appveyor.com/api/environments/12168
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 204
      message: No Content
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Expires:
      - "-1"
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Mon, 28 Nov 2016 16:28:26 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 28 Nov 2016 16:28:27 GMT
recorded_with: VCR 3.0.3
