---
http_interactions:
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Fri, 30 Sep 2016 13:22:02 GMT
      Content-Length:
      - '2251'
    body:
      encoding: UTF-8
      string: '[{"deploymentEnvironmentId":7437,"accountId":33256,"name":"chef-appveyor-ci-cookbook","provider":"Agent","projectsMode":0,"securityDescriptor":{"accessRightDefinitions":[{"name":"View","description":"View"},{"name":"Deploy","description":"Deploy
        build"},{"name":"Update","description":"Update"},{"name":"Delete","description":"Delete"}],"roleAces":[{"roleId":53960,"name":"Administrator","isAdmin":true,"accessRights":[{"name":"View","allowed":true},{"name":"Deploy","allowed":true},{"name":"Update","allowed":true},{"name":"Delete","allowed":true}]},{"roleId":53961,"name":"User","isAdmin":false,"accessRights":[{"name":"View"},{"name":"Deploy"},{"name":"Update"},{"name":"Delete"}]}]},"created":"2016-01-25T15:48:33.5056397+00:00","updated":"2016-09-23T15:18:43.9334161+00:00"},{"deploymentEnvironmentId":10988,"accountId":33256,"name":"dev","provider":"Agent","projectsMode":0,"securityDescriptor":{"accessRightDefinitions":[{"name":"View","description":"View"},{"name":"Deploy","description":"Deploy
        build"},{"name":"Update","description":"Update"},{"name":"Delete","description":"Delete"}],"roleAces":[{"roleId":53960,"name":"Administrator","isAdmin":true,"accessRights":[{"name":"View","allowed":true},{"name":"Deploy","allowed":true},{"name":"Update","allowed":true},{"name":"Delete","allowed":true}]},{"roleId":53961,"name":"User","isAdmin":false,"accessRights":[{"name":"View"},{"name":"Deploy"},{"name":"Update"},{"name":"Delete"}]}]},"created":"2016-09-26T14:26:19.8003584+00:00","updated":"2016-09-27T10:41:46.8829381+00:00"},{"deploymentEnvironmentId":10989,"accountId":33256,"name":"test","provider":"Agent","projectsMode":0,"securityDescriptor":{"accessRightDefinitions":[{"name":"View","description":"View"},{"name":"Deploy","description":"Deploy
        build"},{"name":"Update","description":"Update"},{"name":"Delete","description":"Delete"}],"roleAces":[{"roleId":53960,"name":"Administrator","isAdmin":true,"accessRights":[{"name":"View","allowed":true},{"name":"Deploy","allowed":true},{"name":"Update","allowed":true},{"name":"Delete","allowed":true}]},{"roleId":53961,"name":"User","isAdmin":false,"accessRights":[{"name":"View"},{"name":"Deploy"},{"name":"Update"},{"name":"Delete"}]}]},"created":"2016-09-26T14:27:38.3644471+00:00"}]'
    http_version: 
  recorded_at: Fri, 30 Sep 2016 13:22:03 GMT
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments/10988/settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Fri, 30 Sep 2016 13:22:06 GMT
      Content-Length:
      - '1226'
    body:
      encoding: UTF-8
      string: '{"environment":{"deploymentEnvironmentId":10988,"accountId":33256,"name":"dev","provider":"Agent","environmentAccessKey":"aacafxvm5elv8h44","settings":{"providerSettings":[{"name":"povider_setting_1","value":{"isEncrypted":false,"value":"setting_1"}}],"environmentVariables":[{"name":"environment-variable-1","value":{"isEncrypted":false,"value":"environment-variable"}}],"notifications":[]},"projectsMode":0,"selectedProjects":[],"projects":[{"projectId":232326,"name":"asp_core","isSelected":false},{"projectId":223829,"name":"chef-appveyor-ci","isSelected":false}],"securityDescriptor":{"accessRightDefinitions":[{"name":"View","description":"View"},{"name":"Deploy","description":"Deploy
        build"},{"name":"Update","description":"Update"},{"name":"Delete","description":"Delete"}],"roleAces":[{"roleId":53960,"name":"Administrator","isAdmin":true,"accessRights":[{"name":"View","allowed":true},{"name":"Deploy","allowed":true},{"name":"Update","allowed":true},{"name":"Delete","allowed":true}]},{"roleId":53961,"name":"User","isAdmin":false,"accessRights":[{"name":"View"},{"name":"Deploy"},{"name":"Update"},{"name":"Delete"}]}]},"created":"2016-09-26T14:26:19.8003584+00:00","updated":"2016-09-27T10:41:46.8829381+00:00"}}'
    http_version: 
  recorded_at: Fri, 30 Sep 2016 13:22:07 GMT
recorded_with: VCR 3.0.3
