---
http_interactions:
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments/12168/settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Strict-Transport-Security:
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      Date:
      - Sun, 26 Nov 2017 10:33:42 GMT
      Content-Length:
      - '64'
    body:
      encoding: UTF-8
      string: '{"message":"Deployment environment not found or access denied."}'
    http_version: 
  recorded_at: Sun, 26 Nov 2017 10:33:43 GMT
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments/32724/settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Strict-Transport-Security:
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      Date:
      - Sun, 26 Nov 2017 10:36:15 GMT
      Content-Length:
      - '64'
    body:
      encoding: UTF-8
      string: '{"message":"Deployment environment not found or access denied."}'
    http_version: 
  recorded_at: Sun, 26 Nov 2017 10:36:15 GMT
recorded_with: VCR 3.0.3
