---
http_interactions:
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      X-Xss-Protection:
      - 1; mode=block
      X-Frame-Options:
      - SAMEORIGIN
      Strict-Transport-Security:
      - max-age=31536000
      X-Content-Type-Options:
      - nosniff
      Date:
      - Sun, 26 Nov 2017 10:33:51 GMT
      Content-Length:
      - '466'
    body:
      encoding: UTF-8
      string: '[{"deploymentEnvironmentId":7437,"name":"chef-appveyor-ci-cookbook","provider":"Agent"},{"deploymentEnvironmentId":10988,"name":"dev","provider":"Agent"},{"deploymentEnvironmentId":32724,"name":"production","provider":"FTP"},{"deploymentEnvironmentId":12193,"name":"production-i1tsnr7ywvmh4f6","provider":"FTP"},{"deploymentEnvironmentId":12189,"name":"production-iygklxsu6jh2btz","provider":"FTP"},{"deploymentEnvironmentId":10989,"name":"test","provider":"Agent"}]'
    http_version: 
  recorded_at: Sun, 26 Nov 2017 10:33:51 GMT
recorded_with: VCR 3.0.3
