---
http_interactions:
- request:
    method: get
    uri: https://ci.appveyor.com/api/environments/12168/settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Authorization:
      - Bearer <APPVEYOR_API_KEY>
      User-Agent:
      - Faraday v0.9.2
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Pragma:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Expires:
      - "-1"
      Server:
      - Microsoft-IIS/8.5
      X-Aspnet-Version:
      - 4.0.30319
      X-Powered-By:
      - ASP.NET
      Date:
      - Mon, 28 Nov 2016 14:28:01 GMT
      Content-Length:
      - '1352'
    body:
      encoding: UTF-8
      string: '{"environment":{"deploymentEnvironmentId":12168,"accountId":33256,"name":"production","provider":"FTP","environmentAccessKey":"uleclq8bxva4oc3x","settings":{"providerSettings":[{"name":"server","value":{"isEncrypted":false,"value":"ftp.server.com"}},{"name":"username","value":{"isEncrypted":false,"value":"ftp-user"}},{"name":"password","value":{"isEncrypted":true,"value":"password"}}],"environmentVariables":[{"name":"my-var","value":{"isEncrypted":false,"value":"123"}}],"notifications":[]},"projectsMode":0,"selectedProjects":[],"projects":[{"projectId":232326,"name":"asp_core","isSelected":false},{"projectId":223829,"name":"chef-appveyor-ci","isSelected":false},{"projectId":253781,"name":"chef-opsview-client","isSelected":false}],"securityDescriptor":{"accessRightDefinitions":[{"name":"View","description":"View"},{"name":"Deploy","description":"Deploy
        build"},{"name":"Update","description":"Update"},{"name":"Delete","description":"Delete"}],"roleAces":[{"roleId":53960,"name":"Administrator","isAdmin":true,"accessRights":[{"name":"View","allowed":true},{"name":"Deploy","allowed":true},{"name":"Update","allowed":true},{"name":"Delete","allowed":true}]},{"roleId":53961,"name":"User","isAdmin":false,"accessRights":[{"name":"View"},{"name":"Deploy"},{"name":"Update"},{"name":"Delete"}]}]},"created":"2016-11-28T12:49:18.8589298+00:00"}}'
    http_version: 
  recorded_at: Mon, 28 Nov 2016 14:28:02 GMT
recorded_with: VCR 3.0.3
